name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: smallzip7799/hongrunxing-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 部署服务器
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          script: |
            echo "删除静态资源文件"
            rm -rf public
            echo "备份public静态资源"
            docker cp hongrunxing-api:/app/public .

            echo "拉取smallzip7799/hongrunxing-api镜像"

            docker pull smallzip7799/hongrunxing-api
            docker inspect -f '{{.Name}}' hongrunxing-api

            if [ $? == 0 ] ;then
              echo "hongrunxing-api容器已存在，需要先删除，下面开始执行删除操作："
              docker container stop hongrunxing-api
              echo "容器已停止"
              docker container rm hongrunxing-api
              echo "容器已删除"
            else
              echo "hongrunxing-api容器不存在，直接构建"
            fi

            echo "运行容器"
            docker run -d -p 7001:7001 --name hongrunxing-api smallzip7799/hongrunxing-api

            echo "删除不用的镜像"
            docker image prune -a -f

            echo "更新静态资源"
            docker cp public hongrunxing-api:/app
